# Generated by Django 4.1.6 on 2023-05-29 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_user_jobtype_user_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
